VehicleRecord/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using VehicleRecord.Models;
using VehicleRecord.VehicleRecordService;

namespace VehicleRecord.Controllers
{
    public class RecordsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private RecordService recordService = new RecordService();

        /// <summary>
        /// Calls service method that
        /// returns list of all records
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            RecordModel model = recordService.GetAllRecords();
            return View(model);
        }

        /// <summary>
        /// Creates record model, and calls service method 
        /// that saves vehicle for specified parameters
        /// </summary>
        /// <param name="recordId"></param>
        /// <param name="vehicleId"></param>
        /// <param name="dateFrom"></param>
        /// <param name="dateTo"></param>
        /// <param name="locationFrom"></param>
        /// <param name="locationTo"></param>
        /// <param name="driverName"></param>
        /// <param name="driverSurname"></param>
        /// <param name="numOfPassangers"></param>
        /// <param name="statusId"></param>
        /// <returns></returns>
        [HttpPost]
        public string SaveRecord(int recordId, int vehicleId, DateTime dateFrom, TimeSpan timeFrom, DateTime dateTo, TimeSpan timeTo, string locationFrom, string locationTo, string driverName, string driverSurname, int numOfPassangers, int statusId)
        {
            Record record = new Record();
            record.Vehicle = new Vehicle();
            record.Status = new Status();
            record.ID = recordId;
            record.Vehicle.ID = vehicleId;
            record.DateFrom = dateFrom;
            record.TimeFrom = timeFrom;
            record.DateTo = dateTo;
            record.TimeTo = timeTo;
            record.LocationFrom = locationFrom;
            record.LocationTo = locationTo;
            record.DriverName = driverName;
            record.DriverSurname = driverSurname;
            record.NumberOfPassangers = numOfPassangers;
            record.Status.ID = statusId;

            return recordService.SaveRecord(record);
        }

        /// <summary>
        /// Calls service method that updates
        /// record status for specified value
        /// </summary>
        /// <param name="id"></param>
        /// <param name="statusId"></param>
        [HttpPost]
        public void UpdateRecordStatus(int id, int statusId)
        {
            recordService.UpdateRecordStatus(id, statusId);
        }
    }
}

VehicleRecord/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VehicleRecord.Models;
using VehicleRecord.VehicleRecordService;

namespace VehicleRecord.Controllers
{
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ReportService reportService = new ReportService();

        /// <summary>
        /// Calls service method that
        /// returns list of all records
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(reportService.GetAllReports());
        }


        /// <summary>
        /// Calls a method that gets list of
        /// reports for specified parameters
        /// </summary>
        /// <param name="vehicleId"></param>
        /// <param name="dateFrom"></param>
        /// <param name="dateTo"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(int vehicleReportId, DateTime dateFromReport, TimeSpan timeFromReport, DateTime dateToReport, TimeSpan timeToReport)
        {
            ReportModel model = new ReportModel();

            model = reportService.GetReport(vehicleReportId, dateFromReport, timeFromReport, dateToReport, timeToReport);

            return View(model);
        }

    }
}

VehicleRecord/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using VehicleRecord.Models;
using VehicleRecord.VehicleRecordService;

namespace VehicleRecord.Controllers
{
    public class VehiclesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private VehicleService vehicleService = new VehicleService();

        /// <summary>
        /// Calls service method that
        /// returns list of all vehicles
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            VehicleModel list = vehicleService.GetAllVehicles();
            return View(list);
        }

        /// <summary>
        /// Creates vehicle model, and calls service method 
        /// that saves vehicle for specified parameters
        /// </summary>
        /// <param name="id"></param>
        /// <param name="brandId"></param>
        /// <param name="brandName"></param>
        /// <param name="brandModelId"></param>
        /// <param name="brandModelName"></param>
        /// <param name="chassisNumber"></param>
        /// <param name="motorNumber"></param>
        /// <param name="motorPower"></param>
        /// <param name="fuelType"></param>
        /// <param name="yearOfProduction"></param>
        /// <returns></returns>
        [HttpPost]
        public void SaveVehicle(int id, int brandId, int brandModelId, int chassisNumber, int motorNumber, int motorPower, int motorPower_Hp, int fuelTypeId, int yearOfProduction)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.ID = id;
            vehicle.Brand = new Brand();
            vehicle.BrandModel = new BrandModel();
            vehicle.FuelType = new FuelType();
            vehicle.Brand.ID = brandId;
            vehicle.BrandModel.ID = brandModelId;
            vehicle.BrandModel.BrandId = brandId;
            vehicle.FuelType.ID = fuelTypeId;
            vehicle.ChassisNumber = chassisNumber;
            vehicle.MotorNumber = motorNumber;
            vehicle.MotorPower = motorPower;
            vehicle.MotorPower_Hp = motorPower_Hp;
            vehicle.YearOfProduction = yearOfProduction;
            vehicleService.SaveVehicle(vehicle);
        }

        /// <summary>
        /// Calls service method that deletes
        /// vehicle for specified id
        /// </summary>
        /// <param name="vehicleId"></param>
        /// <returns></returns>
        [HttpPost]
        public void DeleteVehicle(int vehicleId)
        {
            vehicleService.DeleteVehicle(vehicleId);
        }

    }
}

VehicleRecord/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="VehicleRecord" ng-controller="AngularController">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplikacija za vozni park</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aplikacija za vozni park", "Index", "Vehicles", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vozila", "Index", "Vehicles")</li>
                    <li>@Html.ActionLink("Putni nalozi", "Index", "Records")</li>
                    <li>@Html.ActionLink("Izvještaj", "Index", "Reports")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content-container" style="padding-right: 15px; padding-left: 15px;margin-right: auto;margin-left: auto;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplikacija za vozni park</p>
        </footer>
    </div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"></script>
    @Scripts.Render("~/bundles/VehicleRecord")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>